version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - nginx_cache:/var/cache/nginx
    depends_on:
      - web-builder
      - php
    networks:
      - webnet

  web-builder:
    build:
      context: ./web-builder
    ports:
      - '4200:4200'
    networks:
      - webnet

  php:
    image: wodby/php:8.1
    working_dir: /var/www/html/docroot
    volumes:
      - ./drupal:/var/www/html
    networks:
      - webnet

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  redis:
    image: redis:alpine
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
