services:
  php:
    image: wodby/drupal-php:8.1
    container_name: wodby-php-8.1
    environment:
      PHP_EXTENSIONS_DISABLE: xhprof,spx
      PHP_MAIL_MIXED_LF_AND_CRLF: 'On'
    volumes:
      - ./drupal:/var/www/html
  nginx:
    image: wodby/nginx:1.29
    container_name: wodby-nginx
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: 'off'
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/docroot
      NGINX_VHOST_PRESET: drupal9
    volumes:
      - ./drupal:/var/www/html
    ports:
      - '4080:80'
networks:
  default:
    external: true
    name: 1panel-network
